### ISSUE TITLE
Install from PyPi breaking due to missing README.rst + version weirdness

### ISSUE THREAD

**Issue by cpbotha** [gareth-rees/minipy#52]
When I try to install minipy with PIP the install breaks because README.rst is missing:

```
~$ mkvirtualenv minipy
New python executable in minipy/bin/python
Installing setuptools............done.
Installing pip...............done.
(minipy)cpbotha@meepv3:~$ pip install minipy
Downloading/unpacking minipy
  Downloading minipy-0.1.tar.gz
  Storing download in cache at ./sync/dump/PIP_DOWNLOAD_CACHE/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fm%2Fminipy%2Fminipy-0.1.tar.gz
  Running setup.py egg_info for package minipy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/cpbotha/.virtualenvs/minipy/build/minipy/setup.py", line 18, in <module>
        long_description = open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/cpbotha/.virtualenvs/minipy/build/minipy/setup.py", line 18, in <module>

    long_description = open('README.rst').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/cpbotha/.virtualenvs/minipy/build/minipy
Storing complete log in /home/cpbotha/.pip/pip.log
```

What's also interesting, is that PIP tries to install minipy 0.1, perhaps this bug has already been fixed. Let's see what happens when I hard code version 0.2 (which shoud be on pypi: https://pypi.python.org/pypi/minipy )

```
$ pip install minipy==0.2
Downloading/unpacking minipy==0.2
  Could not find a version that satisfies the requirement minipy==0.2 (from versions: 0.1)
Cleaning up...
No distributions matching the version for minipy==0.2
Storing debug log for failure in /home/cpbotha/.pip/pip.log
```

My pip should be up to date:

```
$ pip --version
pip 1.5.4 from /home/cpbotha/.virtualenvs/minipy/local/lib/python2.7/site-packages (python 2.7)
```

Any ideas how I can fix this?

**Comment by richb-hanover** [comment]
CP Botha's fork installs from pip, and is available as "minipy-ppf". https://github.com/cpbotha/minipy

**Comment by gareth-rees** [comment]
What no pull requests?

**Comment by cpbotha** [comment]
There you go: https://github.com/gareth-rees/minipy/pull/53

minipy-ppf was a temporary workaround because it was so quiet around the issue report here, and then it got really busy, hence the PR only now.

**Comment by richb-hanover** [comment]
Hello - Two questions:
- Has the new minipy been pushed to pypi? I just tried to retrieve it, and it got the error again, mentioning version 0.1... 
- Should the version number be bumped to differentiate this version from all others?

Thanks!

**Comment by richb-hanover** [comment]
One more question/thought: I would have found it helpful to add the installation info to the README since I'm not totally up to speed on Python tools. Changing the first lines to say this would have helped.

a Python 2 minifier by Gareth Rees http://garethrees.org/ Install via pip, for example::
    `pip install minipy`
